// ------------------------------------------------------------------------------
// This file was autogenerated.
// ------------------------------------------------------------------------------
// 
namespace SharpQuery.Collections {
	using System;
	using System.Collections;
	using SharpQuery.SchemaClass;
	
	
	/// <summary>
	///     <para>
	///       A collection that stores <see cref='.SharpQueryParameter'/> objects.
	///    </para>
	/// </summary>
	/// <seealso cref='.SharpQueryParameterCollection'/>
	[Serializable()]
	public class SharpQueryParameterCollection : CollectionBase {
		
		/// <summary>
		///     <para>
		///       Initializes a new instance of <see cref='.SharpQueryParameterCollection'/>.
		///    </para>
		/// </summary>
		public SharpQueryParameterCollection() {
		}
		
		/// <summary>
		///     <para>
		///       Initializes a new instance of <see cref='.SharpQueryParameterCollection'/> based on another <see cref='.SharpQueryParameterCollection'/>.
		///    </para>
		/// </summary>
		/// <param name='value'>
		///       A <see cref='.SharpQueryParameterCollection'/> from which the contents are copied
		/// </param>
		public SharpQueryParameterCollection(SharpQueryParameterCollection value) {
			this.AddRange(value);
		}
		
		/// <summary>
		///     <para>
		///       Initializes a new instance of <see cref='.SharpQueryParameterCollection'/> containing any array of <see cref='.SharpQueryParameter'/> objects.
		///    </para>
		/// </summary>
		/// <param name='value'>
		///       A array of <see cref='.SharpQueryParameter'/> objects with which to intialize the collection
		/// </param>
		public SharpQueryParameterCollection(SharpQueryParameter[] value) {
			this.AddRange(value);
		}
		
		
		public SharpQueryParameterCollection(SharpQuerySchemaClassCollection value) {
			this.AddRange( value );
		}						
		
		/// <summary>
		/// <para>Represents the entry at the specified index of the <see cref='.SharpQueryParameter'/>.</para>
		/// </summary>
		/// <param name='index'><para>The zero-based index of the entry to locate in the collection.</para></param>
		/// <value>
		///    <para> The entry at the specified index of the collection.</para>
		/// </value>
		/// <exception cref='System.ArgumentOutOfRangeException'><paramref name='index'/> is outside the valid range of indexes for the collection.</exception>
		public SharpQueryParameter this[int index] {
			get {
				return ((SharpQueryParameter)(List[index]));
			}
			set {
				List[index] = value;
			}
		}
		
		public SharpQuerySchemaClassCollection ToBaseSchemaCollection()
		{
			SharpQuerySchemaClassCollection returnValues = new SharpQuerySchemaClassCollection();
			foreach( SharpQueryParameter par in this )
			{
				returnValues.Add( par );	
			}
			
			return returnValues;
		}
		
		/// <summary>
		///    <para>Adds a <see cref='.SharpQueryParameter'/> with the specified value to the 
		///    <see cref='.SharpQueryParameterCollection'/> .</para>
		/// </summary>
		/// <param name='value'>The <see cref='.SharpQueryParameter'/> to add.</param>
		/// <returns>
		///    <para>The index at which the new element was inserted.</para>
		/// </returns>
		/// <seealso cref='.SharpQueryParameterCollection.AddRange'/>
		public int Add(SharpQueryParameter value) {
			return List.Add(value);
		}
		
		/// <summary>
		/// <para>Copies the elements of an array to the end of the <see cref='.SharpQueryParameterCollection'/>.</para>
		/// </summary>
		/// <param name='value'>
		///    An array of type <see cref='.SharpQueryParameter'/> containing the objects to add to the collection.
		/// </param>
		/// <returns>
		///   <para>None.</para>
		/// </returns>
		/// <seealso cref='.SharpQueryParameterCollection.Add'/>
		public void AddRange(SharpQueryParameter[] value) {
			for (int i = 0; (i < value.Length); i = (i + 1)) {
				this.Add(value[i]);
			}
		}
		
		/// <summary>
		///     <para>
		///       Adds the contents of another <see cref='.SharpQueryParameterCollection'/> to the end of the collection.
		///    </para>
		/// </summary>
		/// <param name='value'>
		///    A <see cref='.SharpQueryParameterCollection'/> containing the objects to add to the collection.
		/// </param>
		/// <returns>
		///   <para>None.</para>
		/// </returns>
		/// <seealso cref='.SharpQueryParameterCollection.Add'/>
		public void AddRange(SharpQueryParameterCollection value) {
			for (int i = 0; (i < value.Count); i = (i + 1)) {
				this.Add(value[i]);
			}
		}
		
		
		public void AddRange(SharpQuerySchemaClassCollection value) 
		{
			foreach( SharpQueryParameter par in value ) 
			{
				this.Add( par );				
			}
		}						
		
		/// <summary>
		/// <para>Gets a value indicating whether the 
		///    <see cref='.SharpQueryParameterCollection'/> contains the specified <see cref='.SharpQueryParameter'/>.</para>
		/// </summary>
		/// <param name='value'>The <see cref='.SharpQueryParameter'/> to locate.</param>
		/// <returns>
		/// <para><see langword='true'/> if the <see cref='.SharpQueryParameter'/> is contained in the collection; 
		///   otherwise, <see langword='false'/>.</para>
		/// </returns>
		/// <seealso cref='.SharpQueryParameterCollection.IndexOf'/>
		public bool Contains(SharpQueryParameter value) {
			return List.Contains(value);
		}
		
		/// <summary>
		/// <para>Copies the <see cref='.SharpQueryParameterCollection'/> values to a one-dimensional <see cref='System.Array'/> instance at the 
		///    specified index.</para>
		/// </summary>
		/// <param name='array'><para>The one-dimensional <see cref='System.Array'/> that is the destination of the values copied from <see cref='.SharpQueryParameterCollection'/> .</para></param>
		/// <param name='index'>The index in <paramref name='array'/> where copying begins.</param>
		/// <returns>
		///   <para>None.</para>
		/// </returns>
		/// <exception cref='System.ArgumentException'><para><paramref name='array'/> is multidimensional.</para> <para>-or-</para> <para>The number of elements in the <see cref='.SharpQueryParameterCollection'/> is greater than the available space between <paramref name='arrayIndex'/> and the end of <paramref name='array'/>.</para></exception>
		/// <exception cref='System.ArgumentNullException'><paramref name='array'/> is <see langword='null'/>. </exception>
		/// <exception cref='System.ArgumentOutOfRangeException'><paramref name='arrayIndex'/> is less than <paramref name='array'/>'s lowbound. </exception>
		/// <seealso cref='System.Array'/>
		public void CopyTo(SharpQueryParameter[] array, int index) {
			List.CopyTo(array, index);
		}
		
		/// <summary>
		///    <para>Returns the index of a <see cref='.SharpQueryParameter'/> in 
		///       the <see cref='.SharpQueryParameterCollection'/> .</para>
		/// </summary>
		/// <param name='value'>The <see cref='.SharpQueryParameter'/> to locate.</param>
		/// <returns>
		/// <para>The index of the <see cref='.SharpQueryParameter'/> of <paramref name='value'/> in the 
		/// <see cref='.SharpQueryParameterCollection'/>, if found; otherwise, -1.</para>
		/// </returns>
		/// <seealso cref='.SharpQueryParameterCollection.Contains'/>
		public int IndexOf(SharpQueryParameter value) {
			return List.IndexOf(value);
		}
		
		/// <summary>
		/// <para>Inserts a <see cref='.SharpQueryParameter'/> into the <see cref='.SharpQueryParameterCollection'/> at the specified index.</para>
		/// </summary>
		/// <param name='index'>The zero-based index where <paramref name='value'/> should be inserted.</param>
		/// <param name=' value'>The <see cref='.SharpQueryParameter'/> to insert.</param>
		/// <returns><para>None.</para></returns>
		/// <seealso cref='.SharpQueryParameterCollection.Add'/>
		public void Insert(int index, SharpQueryParameter value) {
			List.Insert(index, value);
		}
		
		/// <summary>
		///    <para>Returns an enumerator that can iterate through 
		///       the <see cref='.SharpQueryParameterCollection'/> .</para>
		/// </summary>
		/// <returns><para>None.</para></returns>
		/// <seealso cref='System.Collections.IEnumerator'/>
		public new SharpQueryParameterEnumerator GetEnumerator() {
			return new SharpQueryParameterEnumerator(this);
		}
		
		/// <summary>
		///    <para> Removes a specific <see cref='.SharpQueryParameter'/> from the 
		///    <see cref='.SharpQueryParameterCollection'/> .</para>
		/// </summary>
		/// <param name='value'>The <see cref='.SharpQueryParameter'/> to remove from the <see cref='.SharpQueryParameterCollection'/> .</param>
		/// <returns><para>None.</para></returns>
		/// <exception cref='System.ArgumentException'><paramref name='value'/> is not found in the Collection. </exception>
		public void Remove(SharpQueryParameter value) {
			List.Remove(value);
		}
		
		public class SharpQueryParameterEnumerator : object, IEnumerator {
			
			private IEnumerator baseEnumerator;
			
			private IEnumerable temp;
			
			public SharpQueryParameterEnumerator(SharpQueryParameterCollection mappings) {
				this.temp = ((IEnumerable)(mappings));
				this.baseEnumerator = temp.GetEnumerator();
			}
			
			public SharpQueryParameter Current {
				get {
					return ((SharpQueryParameter)(baseEnumerator.Current));
				}
			}
			
			object IEnumerator.Current {
				get {
					return baseEnumerator.Current;
				}
			}
			
			public bool MoveNext() {
				return baseEnumerator.MoveNext();
			}
			
			bool IEnumerator.MoveNext() {
				return baseEnumerator.MoveNext();
			}
			
			public void Reset() {
				baseEnumerator.Reset();
			}
			
			void IEnumerator.Reset() {
				baseEnumerator.Reset();
			}
		}
	}
}
